AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Resources:

  UserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: !Ref AWS::StackName
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: false
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: false

  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      UserPoolId: !Ref UserPool

  IdentityPool:
   Type: "AWS::Cognito::IdentityPool"
   Properties:
     IdentityPoolName: !Ref AWS::StackName
     AllowUnauthenticatedIdentities: false
     CognitoIdentityProviders:
       - ClientId: !Ref UserPoolClient
         ProviderName: !GetAtt UserPool.ProviderName

  IdentityPoolAuthenticatedRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated: "cognito-identity.amazonaws.com"
            Action: "sts:AssumeRoleWithWebIdentity"
      Policies:
        - PolicyName: snsPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "sns:ListTopics"
                  - "sns:Publish"
                Resource: '*'
        - PolicyName: eventBridgePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "events:ListEventBuses"
                  - "events:PutEvents"
                Resource: '*'

  IdentityPoolRoles:
    Type: "AWS::Cognito::IdentityPoolRoleAttachment"
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt IdentityPoolAuthenticatedRole.Arn

  UserCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Cognito User Pool Event Generator credentials"
      Name: !Sub "${AWS::StackName}-event-generator-credentials"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "user"}'
        GenerateStringKey: 'password'
        ExcludePunctuation: true

  CreateUser:
    Type: "Custom::CreateUser"
    Properties:
      ServiceToken: !GetAtt 'CreateUserFunction.Arn'
      UserPoolId: !Ref UserPool
      ClientId: !Ref UserPoolClient
      SecretId: !Ref UserCredentials

  CreateUserFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: "index.lambda_handler"
      Timeout: 30
      Runtime: "python3.6"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "cognito-idp:AdminConfirmSignUp"
              Resource: !GetAtt UserPool.Arn
            - Effect: "Allow"
              Action:
                - "cognito-idp:SignUp"
              Resource: "*"
            - Effect: "Allow"
              Action:
                - "secretsmanager:GetSecretValue"
              Resource: !Ref UserCredentials
      InlineCode: |
        import logging
        import json
        import cfnresponse
        import boto3

        logger = logging.getLogger()
        logger.setLevel(logging.INFO)

        cognitoIdp = boto3.client('cognito-idp')
        secretsmanager = boto3.client('secretsmanager')

        def lambda_handler(event, context):
          logger.info('{}'.format(event))
          responseData = {}

          try:
            if event['RequestType'] == 'Create':
              userPoolId = event['ResourceProperties'].get('UserPoolId')
              clientId = event['ResourceProperties'].get('ClientId')
              secretId = event['ResourceProperties'].get('SecretId')

              response = secretsmanager.get_secret_value(
                SecretId=secretId
              )

              secretString=json.loads(response['SecretString'])

              response = cognitoIdp.sign_up(
                ClientId=clientId,
                Username=secretString['username'],
                Password=secretString['password']
              )

              response = cognitoIdp.admin_confirm_sign_up(
                UserPoolId=userPoolId,
                Username=secretString['username']
              )

              responseData['username'] = secretString['username']
              responseData['password'] = secretString['password']

            else: # delete / update
              rs = event['PhysicalResourceId']

            logger.info('responseData {}'.format(responseData))
            cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
          except:
            logger.error("custom resource failed", exc_info=True)
            cfnresponse.send(event, context, cfnresponse.FAILED, responseData)

Outputs:

  EventGeneratorConfigurationUrl:
    Description: Event Generator configuration link
    Value: !Sub "http://event-generator.awsworkshops.io/#/config?region=${AWS::Region}&userPoolId=${UserPool}&userPoolWebClientId=${UserPoolClient}&identityPoolId=${IdentityPool}"

  EventGeneratorUsername:
    Description: Event Generator username
    Value: !GetAtt CreateUser.username

  EventGeneratorPassword:
    Description: Event Generator password
    Value: !GetAtt CreateUser.password
