AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

  DodgyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DodgyFunction
      Handler: index.lambda_handler
      Runtime: python3.7
      Timeout: 10
      InlineCode: |
        import logging

        logger = logging.getLogger()
        logger.setLevel(logging.INFO)

        def lambda_handler(event, context):
          logger.info('{}'.format(event))
          return event
